# Generated by Django 2.2.5 on 2019-09-20 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190919_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('University', models.CharField(max_length=500)),
                ('Department', models.CharField(max_length=500)),
                ('Semester', models.CharField(max_length=500)),
                ('Student_Or_Group_Name', models.CharField(max_length=500)),
                ('Project_Name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Computer_Science')),
            ],
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
